language: java
addons:
  apt:
    packages:
      - ant
script: ant test
notifications:
  irc:
    channels:
      - "irc.freenode.org#jnr"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
matrix:
  include:
  - os: linux-ppc64le
    jdk: openjdk8
sudo: false
cache:
  directories:
  - $HOME/.m2
